name: bugbot

# TODO: Do we want to support edited?
on:
  issues:
    types: ['opened']
  issue_comment:
    types: ['created']

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    # Check out code from the repo this workflow file is in.
    - name: Checkout code
      uses: actions/checkout@v2
    # Fetch tags if repo uses setuptools_scm for package versioning.
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    # Install Python.
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # Install dependencies.
    # TODO: For production, also need to install a dev version of package.
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install PyGithub pytest-astropy-header pytest-remotedata
    # Run bot script.
    # TODO: For production, repo will call an external bugbot.
    - name: Bug bot
      run: |
        python bugbot.py
        if [ -f test_me.py ]; then pytest test_me.py; fi
